export const GET_BLOG_REQUEST = "GET_BLOG_REQUEST";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_FAILURE = "GET_BLOG_FAILURE";

export const POST_BLOG_REQUEST = "POST_BLOG_REQUEST";
export const POST_BLOG_SUCCESS = "POST_BLOG_SUCCESS";
export const POST_BLOG_FAILURE = "POST_BLOG_FAILURE";

export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";

export const EDIT_BLOG_SUCCESS = "EDIT_BLOG_SUCCESS";
